use_gpu: True
device: 0
seed: 42

federate:
  mode: standalone
  total_round_num: 338
  client_num: 1
  share_local_model: True
  save_to: "ckpts/full/baselines/qwen_moe_instr_local.ckpt"

data:
  root: data/
  type: "alpaca_data.json@llm"
  splits: [0.98, 0.01, 0.01]
  splitter: "iid"

model:
  type: "Qwen/Qwen1.5-MoE-A2.7B@huggingface_llm"

llm:
  tok_len: 1024
  retry_on_nan_loss: True
  adapter:
    use: True
    args:
      - {adapter_package: "peft", adapter_method: "lora",
         r: 8, lora_alpha: 32, lora_dropout: 0.05,
         target_modules: ["q_proj","k_proj","v_proj","o_proj"],
         modules_to_save: ["embed_tokens","lm_head"]}

trainer:
  type: llmtrainer

train:
  local_update_steps: 10
  batch_or_epoch: batch
  is_enable_half: False
  optimizer: {type: Adam, lr: 5.0e-6, betas: [0.9, 0.95], eps: 1.0e-5}

dataloader:
  batch_size: 1

grad:
  grad_clip: 1.0

eval:
  freq: 1000
  count_flops: False
