data:
  root: data
  type: tulu3_federated
  tulu3_federated:
    root: tulu3_federated_group
    manifest: manifest.json
    clients:
      - safety_client
    sharding:
      enable: True
      spec: "safety_client=3"
      default_shards: 1
      seed: 42

model:
  type: "meta-llama/Llama-2-7b-hf@huggingface_llm"

llm:
  tok_len: 2048

federate:
  client_num: 1

dataloader:
  batch_size: 1
